# src/main/resources/graphql-client-test-defaults.properties
graphql.test.assets.schema-location=classpath*:graphql/**/*.graphqls
#graphql.test.assets.schema-location=classpath*:graphql/**/*.graphqls,classpath*:graphql/**/*.graphql,classpath*:graphql/**/*.gqls,classpath*:graphql/**/*.gql
graphql.test.assets.persisted-query-hashes-location=classpath:persisted-query-hashes.properties
graphql.test.assets.persisted-queries-pattern=classpath*:persisted-queries/*.gql